import Head from "next/head";
import styles from "./styles.module.scss";
import { Footer } from "../../molecules/footer";
import { Header } from "../../molecules/header";
import FormLogin from "../../organisms/form-login";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <FormLogin />
      </main>
      <Footer />
    </div>
  );
}
