import Head from "next/head";
import { Footer } from "../../molecules/footer";
import FormRegister from "../../organisms/form-register";
import Styles from "./styles.module.scss";

const Register = () => {
  return (
    <div className={Styles.container}>
      <Head>
        <title>Registre-se</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={Styles.main}>
        <h1>Registre-se</h1>
        <FormRegister />
      </main>
      <Footer />
    </div>
  );
};

export default Register;
